spring:
  #服务名
  application:
    name: gateway

  # nacos
  cloud:
    nacos:
      server-addr: 192.168.80.128:8848
      discovery:
        username: nacos
        password: nacos
        # 服务列表 命名空间
        namespace: dev
        # 非临时服务
        ephemeral: false
    sentinel:
      transport:
        dashboard: 192.168.80.128:8858
        port: 8858

    gateway:
      discovery:
        locator:
          enabled: true  #开启自动代理
      # 超时
      httpclient:
        connect-timeout: 6000
        response-timeout: 60s
      # 跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3628800
      routes:
        - id: app1-service
          uri: lb://app1-service
          predicates:
            - Path=/** # 路由的前缀 这里一般只配置一个

server:
  port: 81  #服务的端口号 如果启动好几个服务集群，要修改成不同的
