version: "3.1"
services:
  nginx_nacos:
    container_name: "nginx_nacos"
    image: nginx
    ports:
      - 8838:8838
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
