server:
  port: 8020
spring:
  application:
    # nacos服务名
    name: app2-service
  cloud:
    nacos:
      server-addr: 192.168.80.128:8848
      discovery:
        username: nacos
        password: nacos
        # 服务列表 命名空间
        namespace: public

#feign
feign:
  client:
    config:
      default:
        connectTimeout: 120000 # feign 的超时设置 与hystrix一致
        readTimeout: 120000 # feign 的超时设置 与hystrix一致

myParameter:
  value1: '我是app 2222222222222222 的, 参数1'
